language: node_js
node_js:
  - "node"
  - "lts/*"

install:
  - npm ci

script:
  - echo Tests are wip

jobs:
  include:
    - stage: Deploy GitHub Release
      install:
        - npm ci
      script:
        - npm run build
        - pwd && ls -l
        - ls -l dist/

stages:
  - name: test
  - name: Deploy GitHub Release
    if: tag =~ /^v.*/
